version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bookshelf_postgres
    environment:
      POSTGRES_DB: bookshelf
      POSTGRES_USER: bookshelf_user
      POSTGRES_PASSWORD: bookshelf_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookshelf_user -d bookshelf"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    container_name: bookshelf_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://bookshelf_user:bookshelf_password@postgres:5432/bookshelf
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: 