"""cleanup unused imports and dependencies

Revision ID: 59cc81dfecdd
Revises: b38e1b634b57
Create Date: 2025-06-07 22:50:35.571600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cc81dfecdd'
down_revision: Union[str, None] = 'b38e1b634b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
